info:
  contact: {}
paths:
  /v1/rates/:
    get:
      description: Get Rates from DOP to all supported currencies
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: et Rates from DOP to all supported currencies
      tags:
      - rates
swagger: "2.0"
